# Generated by Django 6.0.6 on 2026-06-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='模型名称')),
                ('version', models.CharField(default='v1', max_length=32, verbose_name='版本')),
                ('task_type', models.CharField(choices=[('text_summary', '文本摘要'), ('text_generation', '文本生成'), ('image_classify', '图像识别'), ('image_generate', '图像生成'), ('code_generate', '代码生成')], max_length=32, verbose_name='任务类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('text_summary', '文本摘要'), ('text_generation', '文本生成'), ('image_classify', '图像识别'), ('image_generate', '图像生成'), ('code_generate', '代码生成')], default='text_summary', max_length=32, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('text_input', models.TextField(blank=True, default='', verbose_name='文本输入')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/', verbose_name='图片')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='推理结果')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI任务',
                'verbose_name_plural': 'AI任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
